# Generated by Django 6.0.2 on 2026-02-26 04:11

import django.db.models.deletion
import services.groups.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_apiconsumer_apidefinition_apigateway_apikey_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.groups.models._uid_group, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('handle', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('private', 'Private')], default='private', max_length=20)),
                ('group_type', models.CharField(choices=[('developer', 'Developer Group'), ('production', 'Production Group'), ('marketing', 'Marketing Group'), ('data', 'Data / Science Group'), ('custom', 'Custom Group')], default='developer', max_length=30)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('resources', models.JSONField(default=dict)),
                ('member_count', models.PositiveIntegerField(default=1)),
                ('project_count', models.PositiveIntegerField(default=0)),
                ('pipeline_count', models.PositiveIntegerField(default=0)),
                ('import_source', models.CharField(blank=True, choices=[('github', 'GitHub Organizations'), ('gitlab', 'GitLab Groups'), ('bitbucket', 'Bitbucket Workspaces'), ('atonix', 'OrcaCompute Cloud')], default='', max_length=20)),
                ('import_external_id', models.CharField(blank=True, default='', max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_group',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupAccessToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.groups.models._uid_token, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('scopes', models.JSONField(default=list)),
                ('token_prefix', models.CharField(blank=True, default='', max_length=30)),
                ('token_hash', models.CharField(blank=True, default='', max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='services.group')),
            ],
            options={
                'db_table': 'groups_access_token',
            },
        ),
        migrations.CreateModel(
            name='GroupAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.CharField(max_length=150)),
                ('action', models.CharField(choices=[('group_created', 'Group Created'), ('group_updated', 'Group Updated'), ('group_deleted', 'Group Deleted'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('member_updated', 'Member Role Updated'), ('invite_sent', 'Invitation Sent'), ('invite_accepted', 'Invitation Accepted'), ('token_created', 'Token Created'), ('token_revoked', 'Token Revoked'), ('settings_changed', 'Settings Changed')], max_length=30)),
                ('target', models.CharField(blank=True, default='', max_length=255)),
                ('detail', models.JSONField(default=dict)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='services.group')),
            ],
            options={
                'db_table': 'groups_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.groups.models._uid_invite, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('maintainer', 'Maintainer'), ('developer', 'Developer'), ('viewer', 'Viewer')], default='developer', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='services.group')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_group_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_invitation',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.groups.models._uid_member, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('maintainer', 'Maintainer'), ('developer', 'Developer'), ('viewer', 'Viewer')], default='developer', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='services.group')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_member',
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['owner', '-created_at'], name='groups_grou_owner_i_17469e_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['visibility'], name='groups_grou_visibil_07f8d0_idx'),
        ),
        migrations.AddIndex(
            model_name='groupaccesstoken',
            index=models.Index(fields=['group', 'revoked'], name='groups_acce_group_i_d55f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='groupauditlog',
            index=models.Index(fields=['group', '-created_at'], name='groups_audi_group_i_c48918_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinvitation',
            index=models.Index(fields=['group', 'status'], name='groups_invi_group_i_9c0bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinvitation',
            index=models.Index(fields=['email', 'status'], name='groups_invi_email_9eafb6_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group', 'role'], name='groups_memb_group_i_6f99de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
    ]
