# Generated by Django 6.0.2 on 2026-03-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_operational_component_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='group',
            name='groups_grou_owner_i_17469e_idx',
        ),
        migrations.RemoveIndex(
            model_name='group',
            name='groups_grou_visibil_07f8d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='groupaccesstoken',
            name='groups_acce_group_i_d55f4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='groupauditlog',
            name='groups_audi_group_i_c48918_idx',
        ),
        migrations.RemoveIndex(
            model_name='groupconfigregistry',
            name='grp_cfg_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='groupconfigregistry',
            name='grp_cfg_proj_idx',
        ),
        migrations.RemoveIndex(
            model_name='groupinvitation',
            name='groups_invi_group_i_9c0bc4_idx',
        ),
        migrations.RemoveIndex(
            model_name='groupinvitation',
            name='groups_invi_email_9eafb6_idx',
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='groupmember',
            name='groups_memb_group_i_6f99de_idx',
        ),
        migrations.RemoveIndex(
            model_name='groupresourceregistry',
            name='grp_reg_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='groupresourceregistry',
            name='grp_reg_status_idx',
        ),
        migrations.RemoveConstraint(
            model_name='groupresourceregistry',
            name='unique_group_resource',
        ),
        migrations.RenameIndex(
            model_name='runningprocess',
            new_name='services_ru_owner_i_1e2394_idx',
            old_name='running_owner_status_idx',
        ),
        migrations.RenameIndex(
            model_name='runningprocess',
            new_name='services_ru_process_405456_idx',
            old_name='running_type_status_idx',
        ),
        migrations.AddField(
            model_name='runningprocess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='componentstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='componentstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='runningprocess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='runningprocess',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='runningprocess',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Extra metadata (branch, commit, etc.)'),
        ),
        migrations.AlterField(
            model_name='runningprocess',
            name='progress_pct',
            field=models.IntegerField(default=0, help_text='0-100'),
        ),
        migrations.AlterField(
            model_name='runningprocess',
            name='resource_ref',
            field=models.CharField(blank=True, help_text='Human-readable resource name or path', max_length=255),
        ),
        migrations.RemoveField(
            model_name='group',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='groupauditlog',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupconfigregistry',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupinvitation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupinvitation',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupresourceregistry',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupresourceregistry',
            name='linked_by',
        ),
        migrations.DeleteModel(
            name='GroupAccessToken',
        ),
        migrations.DeleteModel(
            name='GroupAuditLog',
        ),
        migrations.DeleteModel(
            name='GroupConfigRegistry',
        ),
        migrations.DeleteModel(
            name='GroupInvitation',
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupResourceRegistry',
        ),
    ]
