apiVersion: v1
kind: Service
metadata:
  name: orcacompute-backend
  namespace: orcacompute
  labels:
    app: orcacompute-backend
spec:
  selector:
    app: orcacompute-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP
