apiVersion: apps/v1
kind: Deployment
metadata:
  name: orcacompute-nginx
  namespace: orcacompute
  labels:
    app: orcacompute-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orcacompute-nginx
  template:
    metadata:
      labels:
        app: orcacompute-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: app-media
              mountPath: /var/www/media
      volumes:
        - name: nginx-config
          configMap:
            name: orcacompute-nginx-config
            items:
              - key: default.conf
                path: default.conf
        - name: app-media
          persistentVolumeClaim:
            claimName: orcacompute-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: orcacompute-nginx
  namespace: orcacompute
spec:
  selector:
    app: orcacompute-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
