apiVersion: v1
kind: Secret
metadata:
  name: orcacompute-secrets
  namespace: orcacompute
type: Opaque
stringData:
  SECRET_KEY: "REPLACE_ME_WITH_A_SECRET"
  POSTGRES_DB: "orcacompute"
  POSTGRES_USER: "orcacompute_user"
  POSTGRES_PASSWORD: "orcacompute_password"
