apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: orcacompute-tls-staging
  namespace: orcacompute
spec:
  secretName: orcacompute-tls-staging
  dnsNames:
  - orcacompute.com
  - www.orcacompute.com
  - api.orcacompute.com
  issuerRef:
    name: letsencrypt-staging-dns-cloudflare
    kind: ClusterIssuer
