apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: orcacompute-tls-selfsigned
  namespace: orcacompute
spec:
  secretName: orcacompute-tls-selfsigned
  duration: 2160h # 90d
  renewBefore: 360h
  subject:
    organizations:
    - OrcaCompute
  dnsNames:
  - orcacompute.com
  - www.orcacompute.com
  - api.orcacompute.com
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
