# ArgoCD Application to apply the IPv6 patches/Config
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orcacompute-ipv6-patches
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/orcacompute/orcacompute.git
    targetRevision: main
    path: k8s/patches
  destination:
    server: https://kubernetes.default.svc
    namespace: orcacompute
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
