apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: orcacompute
spec:
  template:
    spec:
      containers:
      - name: backend
        image: atonixdev/orcacompute-backend:1.0.1
